#!/bin/bash

METHOD=${1:-EMPTY_METHOD}
ENDPOINT=${2:-EMPTY_ENDPOINT}
PROTOCOL=${3} # CURRENTLY IGNORED, HTTP/1.1 is assumed
REQUEST_RESPONSE_MAPPINGS_DIR=$4

CONFIGURED_RESPONSE=$(grep --no-messages --no-filename -r -oP "$METHOD $ENDPOINT \K.*" $REQUEST_RESPONSE_MAPPINGS_DIR)

echo "$CONFIGURED_RESPONSE"

